apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  tags:
    - python
    - fastapi
spec:
  type: service
  lifecycle: development
  owner: platform-team
